alias l 'exa -lah --git --sort=type'
alias lt 'exa --tree --level=2 --sort=type'
alias v 'nvim'
alias vf 'nvim $(fzf)'
alias cfg 'nvim ~/.config/nvim/'
alias zcfg 'nvim ~/.zshrc'
alias fcfg 'nvim ~/.config/fish/'
alias tcfg 'nvim ~/.tmux.conf'
alias rfish '. ~/.config/fish/config.fish'
alias bat 'bat --theme=Nord --color=always --style=numbers'
alias cls 'clear'
alias lclt 'lt -s my-test-domain -p 3000'
